#!/bin/bash

NAME=$(basename $0)

configure() {
	local CONF_PATH_LIST=( "$HOME"/.config/str/config /etc/str.conf )
	for path in "${CONF_PATH_LIST[@]}"; do
		if [ -f "$path" ]; then
			source "$path"
			break
		fi
	done
	STREAMERS=${STREAMERS-( )}
	LIST_FILE=${LIST_FILE-/tmp/str_list}
}

HELP() {
	cat <<EOF
Usage:
  $NAME [SERVICE] [ID] [QUALITY]
  $NAME -l [OPTIONS]
  $NAME -u [SERVICE] [ID]

A simple wrapper over streamlink.

Options:
  -l, --list		list specified STREAMERS
  -u, --url		print formatted URL
  -h, --help 		show this help and exit

--list options:
  -b, --brief		shorten output where possible
  -q, --quiet		quiet, don't output info messages

Supported services:
	twitch.tv (twitch, tw)
	youtube.com (youtube, yt)

For more details see str(1).

Copyright 2018 Oleksii Filonenko.
This program is distributed under the MIT license.
EOF
	exit 0
}

list() {
	rm -f $LIST_FILE
	[[ ! $QUIET ]] && >&2 printf "Loading list..."
	for i in "${!STREAMERS[@]}"; do
		[[ ! $QUIET ]] && >&2 printf '.'
		printpos=$(($i + 1))
		s="${STREAMERS[$i]}"
		local url="twitch.tv/$s"
		youtube-dl -F $url &> /dev/null
		ret=$?
		case $ret in
			0)
				desc=$(youtube-dl --get-description $url 2>/dev/null)
				print_streamer "$s" online "$desc"
				;;
			*)
				print_streamer "$s" offline
				;;
	esac
	done
	[[ ! $QUIET ]] && echo
	cat $LIST_FILE
	rm -f $LIST_FILE
}

print_streamer() {
	local streamer=$1
	local status=$2
	local description=$3
	if [ $BREV ]; then
		stat=${status:0:2}
		if [ "$stat" = "of" ]; then
			stat=off
		fi
		output="${streamer}|${stat^^}"
	else
		output="$streamer is $status"
		if [ -n "$description" ]; then
			output+=": $description"
		fi
	fi
	(printf "${output}\n" | tr '|' '\t') >> $LIST_FILE
}

options=$(getopt -o lubqhc: --long list,url,brief,quiet,help,config: -n "$NAME" -- "$@")
[[ "$options" = ' --' ]] && HELP
eval set -- "$options"
while true; do
	case "$1" in
		-l | --list)
			LIST=1
			;;
		-u | --url)
			RET_URL=1
			;;
		-b | --brief)
			BREV=1
			;;
		-q | --quiet)
			QUIET=1
			;;
		-c | --config)
			shift
			CONF_FILE="$1"
			;;
		-h | --help)
			HELP
			;;
		--)
			shift
			break
			;;
		*)
			break
			;;
	esac
	shift
done

main() {
	service="$1"
	nick="$2"
	quality="$3"

	if [ -n "$service" ]; then
		case "$service" in
			"tw" | "twitch")
				host="twitch.tv"
				;;
			"yt" | "youtube")
				host="youtube.com"
				;;
			*)
				>2 printf "Wrong service: %s. Setting to twitch.tv.\n" "$service"
				host="twitch.tv"
				;;
		esac
	else
		host="twitch.tv"
	fi

	if [ -z "$quality" ]; then
		quality="best"
	fi

	url="$host"/"$nick" 

	if [[ -n $RET_URL ]]
	then
		echo $url
		exit 0
	elif [[ -n $LIST ]]
	then
		list
		exit 0
	else
		nohup streamlink $url "$quality" &>/dev/null &
		exit 0
	fi
}

configure "$CONF_FILE"
main "$@"
